config/routes.rb
Scissorboy::Application.routes.draw do
  resources :sci_episodes

  resources :episodes

end

app/models/episode.rb
class Episode < ActiveRecord::Base
end

app/models/sci_episode.rb
class SciEpisode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @episodes }
    end
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @episode = Episode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @episode }
    end
  end

  # GET /episodes/new
  # GET /episodes/new.json
  def new
    @episode = Episode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @episode }
    end
  end

  # GET /episodes/1/edit
  def edit
    @episode = Episode.find(params[:id])
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render json: @episode, status: :created, location: @episode }
      else
        format.html { render action: "new" }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /episodes/1
  # PUT /episodes/1.json
  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sci_episodes_controller.rb
class SciEpisodesController < ApplicationController
  # GET /sci_episodes
  # GET /sci_episodes.json
  def index
    @sci_episodes = SciEpisode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sci_episodes }
    end
  end

  # GET /sci_episodes/1
  # GET /sci_episodes/1.json
  def show
    @sci_episode = SciEpisode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sci_episode }
    end
  end

  # GET /sci_episodes/new
  # GET /sci_episodes/new.json
  def new
    @sci_episode = SciEpisode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sci_episode }
    end
  end

  # GET /sci_episodes/1/edit
  def edit
    @sci_episode = SciEpisode.find(params[:id])
  end

  # POST /sci_episodes
  # POST /sci_episodes.json
  def create
    @sci_episode = SciEpisode.new(params[:sci_episode])

    respond_to do |format|
      if @sci_episode.save
        format.html { redirect_to @sci_episode, notice: 'Sci episode was successfully created.' }
        format.json { render json: @sci_episode, status: :created, location: @sci_episode }
      else
        format.html { render action: "new" }
        format.json { render json: @sci_episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sci_episodes/1
  # PUT /sci_episodes/1.json
  def update
    @sci_episode = SciEpisode.find(params[:id])

    respond_to do |format|
      if @sci_episode.update_attributes(params[:sci_episode])
        format.html { redirect_to @sci_episode, notice: 'Sci episode was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sci_episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sci_episodes/1
  # DELETE /sci_episodes/1.json
  def destroy
    @sci_episode = SciEpisode.find(params[:id])
    @sci_episode.destroy

    respond_to do |format|
      format.html { redirect_to sci_episodes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/sci_episodes_helper.rb
module SciEpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :episode_id %><br />
    <%= f.number_field :episode_id %>
  </div>
  <div class="field">
    <%= f.label :episode_number %><br />
    <%= f.number_field :episode_number %>
  </div>
  <div class="field">
    <%= f.label :artist1 %><br />
    <%= f.number_field :artist1 %>
  </div>
  <div class="field">
    <%= f.label :artist2 %><br />
    <%= f.number_field :artist2 %>
  </div>
  <div class="field">
    <%= f.label :episode_host_id %><br />
    <%= f.number_field :episode_host_id %>
  </div>
  <div class="field">
    <%= f.label :salon_id %><br />
    <%= f.number_field :salon_id %>
  </div>
  <div class="field">
    <%= f.label :episode_title %><br />
    <%= f.text_area :episode_title %>
  </div>
  <div class="field">
    <%= f.label :episode_short_title %><br />
    <%= f.text_area :episode_short_title %>
  </div>
  <div class="field">
    <%= f.label :episode_browser_title %><br />
    <%= f.text_area :episode_browser_title %>
  </div>
  <div class="field">
    <%= f.label :pretty_url %><br />
    <%= f.text_area :pretty_url %>
  </div>
  <div class="field">
    <%= f.label :episode_meta_desc %><br />
    <%= f.text_area :episode_meta_desc %>
  </div>
  <div class="field">
    <%= f.label :episode_meta_keywords %><br />
    <%= f.text_area :episode_meta_keywords %>
  </div>
  <div class="field">
    <%= f.label :episode_url %><br />
    <%= f.text_area :episode_url %>
  </div>
  <div class="field">
    <%= f.label :episode_still_img %><br />
    <%= f.text_area :episode_still_img %>
  </div>
  <div class="field">
    <%= f.label :video_code_flash %><br />
    <%= f.text_area :video_code_flash %>
  </div>
  <div class="field">
    <%= f.label :video_code_quick_time %><br />
    <%= f.text_area :video_code_quick_time %>
  </div>
  <div class="field">
    <%= f.label :video_code_iphone %><br />
    <%= f.text_area :video_code_iphone %>
  </div>
  <div class="field">
    <%= f.label :video_code_black_berry %><br />
    <%= f.text_area :video_code_black_berry %>
  </div>
  <div class="field">
    <%= f.label :video_code_android %><br />
    <%= f.text_area :video_code_android %>
  </div>
  <div class="field">
    <%= f.label :video_code_ipad %><br />
    <%= f.text_area :video_code_ipad %>
  </div>
  <div class="field">
    <%= f.label :episode_notes %><br />
    <%= f.text_area :episode_notes %>
  </div>
  <div class="field">
    <%= f.label :episode_pic %><br />
    <%= f.text_area :episode_pic %>
  </div>
  <div class="field">
    <%= f.label :episode_alt_img_tag %><br />
    <%= f.text_area :episode_alt_img_tag %>
  </div>
  <div class="field">
    <%= f.label :publish_date %><br />
    <%= f.date_select :publish_date %>
  </div>
  <div class="field">
    <%= f.label :auto_publish %><br />
    <%= f.number_field :auto_publish %>
  </div>
  <div class="field">
    <%= f.label :vip_episode %><br />
    <%= f.number_field :vip_episode %>
  </div>
  <div class="field">
    <%= f.label :downloadable %><br />
    <%= f.number_field :downloadable %>
  </div>
  <div class="field">
    <%= f.label :vip_group %><br />
    <%= f.number_field :vip_group %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_area :category %>
  </div>
  <div class="field">
    <%= f.label :video_length %><br />
    <%= f.text_area :video_length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <tr>
    <th>Episode</th>
    <th>Episode number</th>
    <th>Artist1</th>
    <th>Artist2</th>
    <th>Episode host</th>
    <th>Salon</th>
    <th>Episode title</th>
    <th>Episode short title</th>
    <th>Episode browser title</th>
    <th>Pretty url</th>
    <th>Episode meta desc</th>
    <th>Episode meta keywords</th>
    <th>Episode url</th>
    <th>Episode still img</th>
    <th>Video code flash</th>
    <th>Video code quick time</th>
    <th>Video code iphone</th>
    <th>Video code black berry</th>
    <th>Video code android</th>
    <th>Video code ipad</th>
    <th>Episode notes</th>
    <th>Episode pic</th>
    <th>Episode alt img tag</th>
    <th>Publish date</th>
    <th>Auto publish</th>
    <th>Vip episode</th>
    <th>Downloadable</th>
    <th>Vip group</th>
    <th>Category</th>
    <th>Video length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @episodes.each do |episode| %>
  <tr>
    <td><%= episode.episode_id %></td>
    <td><%= episode.episode_number %></td>
    <td><%= episode.artist1 %></td>
    <td><%= episode.artist2 %></td>
    <td><%= episode.episode_host_id %></td>
    <td><%= episode.salon_id %></td>
    <td><%= episode.episode_title %></td>
    <td><%= episode.episode_short_title %></td>
    <td><%= episode.episode_browser_title %></td>
    <td><%= episode.pretty_url %></td>
    <td><%= episode.episode_meta_desc %></td>
    <td><%= episode.episode_meta_keywords %></td>
    <td><%= episode.episode_url %></td>
    <td><%= episode.episode_still_img %></td>
    <td><%= episode.video_code_flash %></td>
    <td><%= episode.video_code_quick_time %></td>
    <td><%= episode.video_code_iphone %></td>
    <td><%= episode.video_code_black_berry %></td>
    <td><%= episode.video_code_android %></td>
    <td><%= episode.video_code_ipad %></td>
    <td><%= episode.episode_notes %></td>
    <td><%= episode.episode_pic %></td>
    <td><%= episode.episode_alt_img_tag %></td>
    <td><%= episode.publish_date %></td>
    <td><%= episode.auto_publish %></td>
    <td><%= episode.vip_episode %></td>
    <td><%= episode.downloadable %></td>
    <td><%= episode.vip_group %></td>
    <td><%= episode.category %></td>
    <td><%= episode.video_length %></td>
    <td><%= link_to 'Show', episode %></td>
    <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
    <td><%= link_to 'Destroy', episode, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Episode:</b>
  <%= @episode.episode_id %>
</p>

<p>
  <b>Episode number:</b>
  <%= @episode.episode_number %>
</p>

<p>
  <b>Artist1:</b>
  <%= @episode.artist1 %>
</p>

<p>
  <b>Artist2:</b>
  <%= @episode.artist2 %>
</p>

<p>
  <b>Episode host:</b>
  <%= @episode.episode_host_id %>
</p>

<p>
  <b>Salon:</b>
  <%= @episode.salon_id %>
</p>

<p>
  <b>Episode title:</b>
  <%= @episode.episode_title %>
</p>

<p>
  <b>Episode short title:</b>
  <%= @episode.episode_short_title %>
</p>

<p>
  <b>Episode browser title:</b>
  <%= @episode.episode_browser_title %>
</p>

<p>
  <b>Pretty url:</b>
  <%= @episode.pretty_url %>
</p>

<p>
  <b>Episode meta desc:</b>
  <%= @episode.episode_meta_desc %>
</p>

<p>
  <b>Episode meta keywords:</b>
  <%= @episode.episode_meta_keywords %>
</p>

<p>
  <b>Episode url:</b>
  <%= @episode.episode_url %>
</p>

<p>
  <b>Episode still img:</b>
  <%= @episode.episode_still_img %>
</p>

<p>
  <b>Video code flash:</b>
  <%= @episode.video_code_flash %>
</p>

<p>
  <b>Video code quick time:</b>
  <%= @episode.video_code_quick_time %>
</p>

<p>
  <b>Video code iphone:</b>
  <%= @episode.video_code_iphone %>
</p>

<p>
  <b>Video code black berry:</b>
  <%= @episode.video_code_black_berry %>
</p>

<p>
  <b>Video code android:</b>
  <%= @episode.video_code_android %>
</p>

<p>
  <b>Video code ipad:</b>
  <%= @episode.video_code_ipad %>
</p>

<p>
  <b>Episode notes:</b>
  <%= @episode.episode_notes %>
</p>

<p>
  <b>Episode pic:</b>
  <%= @episode.episode_pic %>
</p>

<p>
  <b>Episode alt img tag:</b>
  <%= @episode.episode_alt_img_tag %>
</p>

<p>
  <b>Publish date:</b>
  <%= @episode.publish_date %>
</p>

<p>
  <b>Auto publish:</b>
  <%= @episode.auto_publish %>
</p>

<p>
  <b>Vip episode:</b>
  <%= @episode.vip_episode %>
</p>

<p>
  <b>Downloadable:</b>
  <%= @episode.downloadable %>
</p>

<p>
  <b>Vip group:</b>
  <%= @episode.vip_group %>
</p>

<p>
  <b>Category:</b>
  <%= @episode.category %>
</p>

<p>
  <b>Video length:</b>
  <%= @episode.video_length %>
</p>


<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scissorboy</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sci_episodes/_form.html.erb
<%= form_for(@sci_episode) do |f| %>
  <% if @sci_episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sci_episode.errors.count, "error") %> prohibited this sci_episode from being saved:</h2>

      <ul>
      <% @sci_episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :episode_id %><br />
    <%= f.number_field :episode_id %>
  </div>
  <div class="field">
    <%= f.label :episode_number %><br />
    <%= f.number_field :episode_number %>
  </div>
  <div class="field">
    <%= f.label :artist1 %><br />
    <%= f.number_field :artist1 %>
  </div>
  <div class="field">
    <%= f.label :artist2 %><br />
    <%= f.number_field :artist2 %>
  </div>
  <div class="field">
    <%= f.label :episode_host_id %><br />
    <%= f.number_field :episode_host_id %>
  </div>
  <div class="field">
    <%= f.label :salon_id %><br />
    <%= f.number_field :salon_id %>
  </div>
  <div class="field">
    <%= f.label :episode_title %><br />
    <%= f.text_area :episode_title %>
  </div>
  <div class="field">
    <%= f.label :episode_short_title %><br />
    <%= f.text_area :episode_short_title %>
  </div>
  <div class="field">
    <%= f.label :episode_browser_title %><br />
    <%= f.text_area :episode_browser_title %>
  </div>
  <div class="field">
    <%= f.label :pretty_url %><br />
    <%= f.text_area :pretty_url %>
  </div>
  <div class="field">
    <%= f.label :episode_meta_desc %><br />
    <%= f.text_area :episode_meta_desc %>
  </div>
  <div class="field">
    <%= f.label :episode_meta_keywords %><br />
    <%= f.text_area :episode_meta_keywords %>
  </div>
  <div class="field">
    <%= f.label :episode_url %><br />
    <%= f.text_area :episode_url %>
  </div>
  <div class="field">
    <%= f.label :episode_still_img %><br />
    <%= f.text_area :episode_still_img %>
  </div>
  <div class="field">
    <%= f.label :video_code_flash %><br />
    <%= f.text_area :video_code_flash %>
  </div>
  <div class="field">
    <%= f.label :video_code_quick_time %><br />
    <%= f.text_area :video_code_quick_time %>
  </div>
  <div class="field">
    <%= f.label :video_code_iphone %><br />
    <%= f.text_area :video_code_iphone %>
  </div>
  <div class="field">
    <%= f.label :video_code_black_berry %><br />
    <%= f.text_area :video_code_black_berry %>
  </div>
  <div class="field">
    <%= f.label :video_code_android %><br />
    <%= f.text_area :video_code_android %>
  </div>
  <div class="field">
    <%= f.label :video_code_ipad %><br />
    <%= f.text_area :video_code_ipad %>
  </div>
  <div class="field">
    <%= f.label :episode_notes %><br />
    <%= f.text_area :episode_notes %>
  </div>
  <div class="field">
    <%= f.label :episode_pic %><br />
    <%= f.text_area :episode_pic %>
  </div>
  <div class="field">
    <%= f.label :episode_alt_img_tag %><br />
    <%= f.text_area :episode_alt_img_tag %>
  </div>
  <div class="field">
    <%= f.label :publish_date %><br />
    <%= f.date_select :publish_date %>
  </div>
  <div class="field">
    <%= f.label :auto_publish %><br />
    <%= f.number_field :auto_publish %>
  </div>
  <div class="field">
    <%= f.label :vip_episode %><br />
    <%= f.number_field :vip_episode %>
  </div>
  <div class="field">
    <%= f.label :downloadable %><br />
    <%= f.number_field :downloadable %>
  </div>
  <div class="field">
    <%= f.label :vip_group %><br />
    <%= f.number_field :vip_group %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_area :category %>
  </div>
  <div class="field">
    <%= f.label :video_length %><br />
    <%= f.text_area :video_length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sci_episodes/edit.html.erb
<h1>Editing sci_episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @sci_episode %> |
<%= link_to 'Back', sci_episodes_path %>

app/views/sci_episodes/index.html.erb
<h1>Listing sci_episodes</h1>

<table>
  <tr>
    <th>Episode</th>
    <th>Episode number</th>
    <th>Artist1</th>
    <th>Artist2</th>
    <th>Episode host</th>
    <th>Salon</th>
    <th>Episode title</th>
    <th>Episode short title</th>
    <th>Episode browser title</th>
    <th>Pretty url</th>
    <th>Episode meta desc</th>
    <th>Episode meta keywords</th>
    <th>Episode url</th>
    <th>Episode still img</th>
    <th>Video code flash</th>
    <th>Video code quick time</th>
    <th>Video code iphone</th>
    <th>Video code black berry</th>
    <th>Video code android</th>
    <th>Video code ipad</th>
    <th>Episode notes</th>
    <th>Episode pic</th>
    <th>Episode alt img tag</th>
    <th>Publish date</th>
    <th>Auto publish</th>
    <th>Vip episode</th>
    <th>Downloadable</th>
    <th>Vip group</th>
    <th>Category</th>
    <th>Video length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sci_episodes.each do |sci_episode| %>
  <tr>
    <td><%= sci_episode.episode_id %></td>
    <td><%= sci_episode.episode_number %></td>
    <td><%= sci_episode.artist1 %></td>
    <td><%= sci_episode.artist2 %></td>
    <td><%= sci_episode.episode_host_id %></td>
    <td><%= sci_episode.salon_id %></td>
    <td><%= sci_episode.episode_title %></td>
    <td><%= sci_episode.episode_short_title %></td>
    <td><%= sci_episode.episode_browser_title %></td>
    <td><%= sci_episode.pretty_url %></td>
    <td><%= sci_episode.episode_meta_desc %></td>
    <td><%= sci_episode.episode_meta_keywords %></td>
    <td><%= sci_episode.episode_url %></td>
    <td><%= sci_episode.episode_still_img %></td>
    <td><%= sci_episode.video_code_flash %></td>
    <td><%= sci_episode.video_code_quick_time %></td>
    <td><%= sci_episode.video_code_iphone %></td>
    <td><%= sci_episode.video_code_black_berry %></td>
    <td><%= sci_episode.video_code_android %></td>
    <td><%= sci_episode.video_code_ipad %></td>
    <td><%= sci_episode.episode_notes %></td>
    <td><%= sci_episode.episode_pic %></td>
    <td><%= sci_episode.episode_alt_img_tag %></td>
    <td><%= sci_episode.publish_date %></td>
    <td><%= sci_episode.auto_publish %></td>
    <td><%= sci_episode.vip_episode %></td>
    <td><%= sci_episode.downloadable %></td>
    <td><%= sci_episode.vip_group %></td>
    <td><%= sci_episode.category %></td>
    <td><%= sci_episode.video_length %></td>
    <td><%= link_to 'Show', sci_episode %></td>
    <td><%= link_to 'Edit', edit_sci_episode_path(sci_episode) %></td>
    <td><%= link_to 'Destroy', sci_episode, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sci episode', new_sci_episode_path %>

app/views/sci_episodes/new.html.erb
<h1>New sci_episode</h1>

<%= render 'form' %>

<%= link_to 'Back', sci_episodes_path %>

app/views/sci_episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Episode:</b>
  <%= @sci_episode.episode_id %>
</p>

<p>
  <b>Episode number:</b>
  <%= @sci_episode.episode_number %>
</p>

<p>
  <b>Artist1:</b>
  <%= @sci_episode.artist1 %>
</p>

<p>
  <b>Artist2:</b>
  <%= @sci_episode.artist2 %>
</p>

<p>
  <b>Episode host:</b>
  <%= @sci_episode.episode_host_id %>
</p>

<p>
  <b>Salon:</b>
  <%= @sci_episode.salon_id %>
</p>

<p>
  <b>Episode title:</b>
  <%= @sci_episode.episode_title %>
</p>

<p>
  <b>Episode short title:</b>
  <%= @sci_episode.episode_short_title %>
</p>

<p>
  <b>Episode browser title:</b>
  <%= @sci_episode.episode_browser_title %>
</p>

<p>
  <b>Pretty url:</b>
  <%= @sci_episode.pretty_url %>
</p>

<p>
  <b>Episode meta desc:</b>
  <%= @sci_episode.episode_meta_desc %>
</p>

<p>
  <b>Episode meta keywords:</b>
  <%= @sci_episode.episode_meta_keywords %>
</p>

<p>
  <b>Episode url:</b>
  <%= @sci_episode.episode_url %>
</p>

<p>
  <b>Episode still img:</b>
  <%= @sci_episode.episode_still_img %>
</p>

<p>
  <b>Video code flash:</b>
  <%= @sci_episode.video_code_flash %>
</p>

<p>
  <b>Video code quick time:</b>
  <%= @sci_episode.video_code_quick_time %>
</p>

<p>
  <b>Video code iphone:</b>
  <%= @sci_episode.video_code_iphone %>
</p>

<p>
  <b>Video code black berry:</b>
  <%= @sci_episode.video_code_black_berry %>
</p>

<p>
  <b>Video code android:</b>
  <%= @sci_episode.video_code_android %>
</p>

<p>
  <b>Video code ipad:</b>
  <%= @sci_episode.video_code_ipad %>
</p>

<p>
  <b>Episode notes:</b>
  <%= @sci_episode.episode_notes %>
</p>

<p>
  <b>Episode pic:</b>
  <%= @sci_episode.episode_pic %>
</p>

<p>
  <b>Episode alt img tag:</b>
  <%= @sci_episode.episode_alt_img_tag %>
</p>

<p>
  <b>Publish date:</b>
  <%= @sci_episode.publish_date %>
</p>

<p>
  <b>Auto publish:</b>
  <%= @sci_episode.auto_publish %>
</p>

<p>
  <b>Vip episode:</b>
  <%= @sci_episode.vip_episode %>
</p>

<p>
  <b>Downloadable:</b>
  <%= @sci_episode.downloadable %>
</p>

<p>
  <b>Vip group:</b>
  <%= @sci_episode.vip_group %>
</p>

<p>
  <b>Category:</b>
  <%= @sci_episode.category %>
</p>

<p>
  <b>Video length:</b>
  <%= @sci_episode.video_length %>
</p>


<%= link_to 'Edit', edit_sci_episode_path(@sci_episode) %> |
<%= link_to 'Back', sci_episodes_path %>